bash4 fixes

diff --git a/bumppkg b/bumppkg
--- a/bumppkg
+++ b/bumppkg
@@ -149,7 +149,7 @@ fi
 
 if [ "$1" == "--rebuild" ]; then
 	shift 1
-	source FrugalBuild || die "failed to source the FrugalBuild!"
+	source ./FrugalBuild || die "failed to source the FrugalBuild!"
 	newrel=$(echo $pkgrel|sed 's/[0-9]\+$//')$(($(echo $pkgrel|sed 's/.*[^0-9]\([0-9]\+\)$/\1/')+1))
 	update_pkgrel $newrel
 	if [ "$tree" == "stable" ] && echo "$pkgrel" | grep -q "^[0-9]\+$"; then
diff --git a/genchangelog b/genchangelog
--- a/genchangelog
+++ b/genchangelog
@@ -38,7 +38,7 @@ if [ ! -e Changelog ] || [ `stat -c %Y Changelog` -lt `stat -c %Y FrugalBuild` ]
 	echo "done."
 fi
 
-CARCH=$arch source FrugalBuild || die "errors parsing the FrugalBuild"
+CARCH=$arch source ./FrugalBuild || die "errors parsing the FrugalBuild"
 
 if [ -e README.Frugalware ]; then
 	if [ ! -e $pkgname.html ] || [ `stat -c %Y $pkgname.html` -lt `stat -c %Y README.Frugalware` ]; then
