genchangelog: added subpkgs support

diff --git a/genchangelog b/genchangelog
--- a/genchangelog
+++ b/genchangelog
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+die()
+{
+	echo "genchangelog: $@"
+	exit 1
+}
+
+# fake functions for fwmakepkg
+error() { return 0; }
+Fdie() { return 0; }
+Finclude() { return 0; }
+
 . /etc/genchangelog.conf
 
 echo -n "running darcs changes... "
@@ -12,13 +23,26 @@ repo=`pwd|sed 's|.*/\(.*\)/.*/.*/.*|\1|'`
 if [ "$repo" != "extra" ]; then
 	repo="frugalware"
 fi
-pkgname=`pwd|sed 's|.*/\(.*\)|\1|'`
+
+source FrugalBuild || die "errors parsing the FrugalBuild"
 
 if [ "$repo" == "frugalware" ]; then
 	cd ../../../frugalware-$arch
 	../tools/fdb2db -b ../source/ -r frugalware -e $fwver -f frugalware-$fwver.fdb -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -c $pkgname
+	if [ ! -z "$subpkgs" ]; then
+		for subpkg in "${subpkgs[@]}"
+		do
+			../tools/fdb2db -b ../source/ -r frugalware -e $fwver -f frugalware-$fwver.fdb -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -c "$subpkg" -s -n $pkgname
+		done
+	fi
 else
 	cd ../../../frugalware-$arch
 	../../tools/fdb2db -b ../source/ -r extra -e $fwver -f extra-$fwver.fdb -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -c $pkgname
+	if [ ! -z "$subpkgs" ]; then
+		for subpkg in "${subpkgs[@]}"
+		do
+			../../tools/fdb2db -b ../source/ -r extra -e $fwver -f extra-$fwver.fdb -a $arch -h $dbhost -u $dbuser -d $dbname -t $dbtable -c $subpkg -s -n $pkgname
+		done
+	fi
 fi
 echo "done."
