bumppkg: remove --record-only, use repoman rec instead

diff --git a/portpkg b/portpkg
--- a/portpkg
+++ b/portpkg
@@ -26,7 +26,7 @@ if ! ls *fpm &>/dev/null; then
 fi
 
 if [ "$1" == "--push" ]; then
-	bumppkg --record-only "added `uname -m` to archs()" || die "failed to record the patch"
+	repoman rec "added `uname -m` to archs()" || die "failed to record the patch"
 	repoman -k push
 else
 	die "now run '$0 --push' to record and push your changes"
