repoman: handle the case when we get no output from mktemp

diff --git a/repoman b/repoman
--- a/repoman
+++ b/repoman
@@ -122,6 +122,10 @@ upload()
 		name=`basename $src`
 		msg "Requesting a temporary file"
 		tmp=`ssh $host $mktemp_remote 2>/dev/null`
+		if [ -z "$temp" ]; then
+			echo "Failed to get a temporary file :-/"
+			exit 1
+		fi
 		msg "Uploading file: $src (to $tmp)"
 		scp $src $host:$tmp
 		if echo "`sha1sum $src|sed 's/\(.*\)  .*/\1/'`  $tmp" |ssh $host sha1sum -c - >/dev/null 2>&1; then
