repoman: factor out *_lock functions to avoid code duplication

diff --git a/repoman b/repoman
--- a/repoman
+++ b/repoman
@@ -100,6 +100,26 @@ check_absolute_path()
 	fi
 }
 
+# lock management
+get_lock()
+{
+	if [ -e .git/lock ]; then
+		echo "Couldn't get lock."
+		return 1
+	fi
+}
+
+put_lock()
+{
+	touch .git/lock
+}
+
+rm_lock()
+{
+	echo "$1"
+	rm -f .git/lock
+}
+
 server()
 {
 	local i
@@ -116,10 +136,7 @@ server()
 		shift 2
 		check_absolute_path
 		cd $path
-		if [ -e .git/lock ]; then
-			echo "Couldn't get lock."
-			return 1
-		fi
+		get_lock || return 1
 		if [ -n "$verbose" ]; then
 			rmopts="-v"
 		else
@@ -159,10 +176,7 @@ server()
 		shift 4
 		check_absolute_path
 		cd $path
-		if [ -e .git/lock ]; then
-			echo "Couldn't get lock."
-			return 1
-		fi
+		get_lock || return 1
 		if ! echo "$sha  $tmp" |sha1sum -c - >/dev/null 2>&1; then
 			echo "The uploaded file is corrupted :-/"
 			rm $tmp
@@ -221,15 +235,10 @@ server()
 		shift 5
 		check_absolute_path
 		cd $path
-		if [ -e .git/lock ]; then
-			echo "Couldn't get lock."
-			return 1
-		else
-			touch .git/lock
-		fi
+		get_lock || return 1
+		put_lock
 		if ! cd source/$group/$pkg; then
-			echo "There is no package with this group!"
-			rm -f .git/lock
+			rm_lock "There is no package with this group!"
 			return 1
 		fi
 		startdir=`pwd`
@@ -271,12 +280,8 @@ server()
 		check_absolute_path
 		cd $path
 		if [ -z "$nofdb" ]; then
-			if [ -e .git/lock ]; then
-				echo "Couldn't get lock."
-				return 1
-			else
-				touch .git/lock
-			fi
+			get_lock || return 1
+			put_lock
 			for i in frugalware-*
 			do
 				if [ -n "$exclusivearch" -a "frugalware-$exclusivearch" != $i ]; then
@@ -285,14 +290,12 @@ server()
 				cd $i
 				if ! _check_nobuild; then
 					if [ ! -e $fdb ]; then
-						echo "No package database to clean from!"
+						rm_lock "No package database to clean from!"
 						cd - >/dev/null
-						rm -f .git/lock
 						return 1
 					else
 						if ! arch=$arch updatesync del $fdb $pkg; then
-							echo "updatesync failed!"
-							rm -f .git/lock
+							rm_lock "updatesync failed!"
 							return 1
 						fi
 					fi
