repoman: abort repoman push if $scm push failed

diff --git a/repoman b/repoman
--- a/repoman
+++ b/repoman
@@ -35,6 +35,7 @@ dry_run()
 {
 	if [ -z "$dryrun" ]; then
 		eval "$*"
+		return $?
 	else
 		echo $*
 	fi
@@ -367,7 +368,7 @@ sync()
 	if [ -n "$noask" ]; then
 		cmd="$cmd -a"
 	fi
-	dry_run "$cmd"
+	dry_run "$cmd" || die "push failed"
 
 	# here we _could_ upload the new sources but that'll be done by changelog()
 
