repoman: refuse to upload packages with broken file(s)/path(s) * added checks for lib64 , /usr/etc and broken DESTDIR * if we find broken things print a nice message so the * packager knows what is going on and simply refuse to * upload the broken fpm(s)

diff --git a/repoman b/repoman
--- a/repoman
+++ b/repoman
@@ -308,6 +308,23 @@ upload()
 			echo "package and try again."
 			exit 1
 		fi
+		if echo $src | grep -q fpm$ && pacman-g2 -Ql -p $src | egrep -q ' lib64/| usr/lib64/'; then
+			echo "$src has invalid lib64 path , refusing to upload!"
+			echo "Please fix your package."
+			exit 1
+		fi
+		if echo $src | grep -q fpm$ && pacman-g2 -Ql -p $src | grep -q 'var/tmp/fst'; then
+			echo "$src has broken DESTDIR , files are installed"
+			echo "in DESTDIR/DESTDIR , refusing to upload!"
+			echo "Please fix your package."
+			exit 1
+		fi
+		if echo $src | grep -q fpm$ && pacman-g2 -Ql -p $src | grep -q 'usr/etc'; then
+			echo "$src has invalid etc path , files are installed"
+			echo "in /usr/etc , refusing to upload!"
+			echo "Please fix your package."
+			exit 1
+		fi
 		name=`basename $src`
 		msg "Requesting a temporary file"
 		tmp=`ssh $host "$sudo_cmd repoman server mktemp"`
