repoman * added check for broken paths :   /usr/usr   /usr/share/pkgconfig   /usr/share/perl5 * and refuse to upload the package

diff --git a/repoman b/repoman
--- a/repoman
+++ b/repoman
@@ -403,6 +403,25 @@ upload()
 			echo "Please fix your package."
 			exit 1
 		fi
+		if echo $src | grep -q fpm$ && pacman-g2 -Ql -p $src | grep -q 'usr/usr'; then
+                        echo "$src has broken /usr DIR , files are installed"
+                        echo "in /usr/usr , refusing to upload!"
+                        echo "Please fix your package."
+                        exit 1
+		fi
+		if echo $src | grep -q fpm$ && pacman-g2 -Ql -p $src | grep -q 'usr/share/pkgconfig'; then
+                        echo "$src has invalid pkgconfig path , files are installed"
+                        echo "in /usr/share/pkgconfig , should be /usr/lib/pkgconfig, refusing to upload!"
+                        echo "Please fix your package."
+                        exit 1
+		fi
+		if echo $src | grep -q fpm$ && pacman-g2 -Ql -p $src | grep -q 'usr/share/perl5'; then
+                        echo "$src has invalid perl path , files are installed"
+                        echo "in /usr/share/perl5 , refusing to upload!"
+                        echo "Please fix your package."
+                        exit 1
+		fi
+
 		name=`basename $src`
 		msg "Requesting a temporary file"
 		tmp=`_ssh "mktemp"`
