whitespace fixes

diff --git a/repoman b/repoman
--- a/repoman
+++ b/repoman
@@ -818,22 +818,22 @@ merge()
 		target=$1
 	fi
 	if [ -z "$force" ]; then
-	# install essential packages if necessary
-	echo -n "checking for essential packages... "
-	. /etc/makepkg.conf
-	for i in "$COREPKGS"
-	do
-		missing="$missing `pacman -Sg $i |grep -v '^\w'` "
-	done
-	missdep=`pacman-g2 -T $missing| sed 's|.\+: ||'`
-	if [ -n "$missdep" ]; then
-		echo "failed"
-		echo "Use the following command to install the missing packages:"
-		echo "pacman-g2 -S `echo $missdep| sed 's|=.*$||;s|>.*$||;s|<.*$||'`"
-		exit 1
-	else
-		echo "done"
-	fi
+		# install essential packages if necessary
+		echo -n "checking for essential packages... "
+		. /etc/makepkg.conf
+		for i in "$COREPKGS"
+		do
+			missing="$missing `pacman -Sg $i |grep -v '^\w'` "
+		done
+		missdep=`pacman-g2 -T $missing| sed 's|.\+: ||'`
+		if [ -n "$missdep" ]; then
+			echo "failed"
+			echo "Use the following command to install the missing packages:"
+			echo "pacman-g2 -S `echo $missdep| sed 's|=.*$||;s|>.*$||;s|<.*$||'`"
+			exit 1
+		else
+			echo "done"
+		fi
 	fi
 	found=0
 	for i in ${repo[@]}
